version: "2"
plugins:
  duplication:
    enabled: true
  sonar-php:
    enabled: true
    checks:
      # Disable string literals reporting
      php:S1192:
        enabled: false
      # Disable unused parameter triggering for cURL callback. Already handled by phan.
      php:S1172:
        enabled: false
      # Throwing ErrorException
      php:S112:
        enabled: false
