language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot

dist: xenial
  
install:
  - composer install
  - composer validate
  
before_script:
  - pecl channel-update pecl.php.net
  - pecl install ast
  - phpenv config-rm xdebug.ini

script:
  - composer test