language: php

php:
  - 7.2
  - 7.3
  - 7.4

dist: bionic

before_install:
  - phpenv config-rm xdebug.ini
  - pecl channel-update pecl.php.net
  - pecl install ast

install:
  - composer install
  - composer validate

script:
  - composer test
  - vendor/bin/phpda
