name: Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
       include:
         - PHP_VERSION: '7.2'
         - PHP_VERSION: '7.3'
         - PHP_VERSION: '7.4'
         - PHP_VERSION: '8.0'
         - PHP_VERSION: '8.1'

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Setup PHP extensions
      run: |
        sudo phpdismod xdebug
        pecl channel-update pecl.php.net
        php -i | grep 'Configuration File'
        sudo pecl install ast

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      run: composer run-script test
